spring:
  datasource:
    url: jdbc:mysql://35.230.33.50:3306/game
    username: root
    password: SJSU@1234CMPE275
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl